// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/table.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include <google/protobuf/duration.pb.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
namespace google {
namespace bigtable {
namespace admin {
namespace v2 {
class ColumnFamily;
class ColumnFamilyDefaultTypeInternal;
extern ColumnFamilyDefaultTypeInternal _ColumnFamily_default_instance_;
class GcRule;
class GcRuleDefaultTypeInternal;
extern GcRuleDefaultTypeInternal _GcRule_default_instance_;
class GcRule_Intersection;
class GcRule_IntersectionDefaultTypeInternal;
extern GcRule_IntersectionDefaultTypeInternal _GcRule_Intersection_default_instance_;
class GcRule_Union;
class GcRule_UnionDefaultTypeInternal;
extern GcRule_UnionDefaultTypeInternal _GcRule_Union_default_instance_;
class Snapshot;
class SnapshotDefaultTypeInternal;
extern SnapshotDefaultTypeInternal _Snapshot_default_instance_;
class Table;
class TableDefaultTypeInternal;
extern TableDefaultTypeInternal _Table_default_instance_;
class Table_ClusterState;
class Table_ClusterStateDefaultTypeInternal;
extern Table_ClusterStateDefaultTypeInternal _Table_ClusterState_default_instance_;
class Table_ClusterStatesEntry_DoNotUse;
class Table_ClusterStatesEntry_DoNotUseDefaultTypeInternal;
extern Table_ClusterStatesEntry_DoNotUseDefaultTypeInternal _Table_ClusterStatesEntry_DoNotUse_default_instance_;
class Table_ColumnFamiliesEntry_DoNotUse;
class Table_ColumnFamiliesEntry_DoNotUseDefaultTypeInternal;
extern Table_ColumnFamiliesEntry_DoNotUseDefaultTypeInternal _Table_ColumnFamiliesEntry_DoNotUse_default_instance_;
}  // namespace v2
}  // namespace admin
}  // namespace bigtable
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> ::google::bigtable::admin::v2::ColumnFamily* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::ColumnFamily>(Arena*);
template<> ::google::bigtable::admin::v2::GcRule* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::GcRule>(Arena*);
template<> ::google::bigtable::admin::v2::GcRule_Intersection* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::GcRule_Intersection>(Arena*);
template<> ::google::bigtable::admin::v2::GcRule_Union* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::GcRule_Union>(Arena*);
template<> ::google::bigtable::admin::v2::Snapshot* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::Snapshot>(Arena*);
template<> ::google::bigtable::admin::v2::Table* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::Table>(Arena*);
template<> ::google::bigtable::admin::v2::Table_ClusterState* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::Table_ClusterState>(Arena*);
template<> ::google::bigtable::admin::v2::Table_ClusterStatesEntry_DoNotUse* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::Table_ClusterStatesEntry_DoNotUse>(Arena*);
template<> ::google::bigtable::admin::v2::Table_ColumnFamiliesEntry_DoNotUse* Arena::CreateMaybeMessage<::google::bigtable::admin::v2::Table_ColumnFamiliesEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace google {
namespace bigtable {
namespace admin {
namespace v2 {

enum Table_ClusterState_ReplicationState : int {
  Table_ClusterState_ReplicationState_STATE_NOT_KNOWN = 0,
  Table_ClusterState_ReplicationState_INITIALIZING = 1,
  Table_ClusterState_ReplicationState_PLANNED_MAINTENANCE = 2,
  Table_ClusterState_ReplicationState_UNPLANNED_MAINTENANCE = 3,
  Table_ClusterState_ReplicationState_READY = 4,
  Table_ClusterState_ReplicationState_Table_ClusterState_ReplicationState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Table_ClusterState_ReplicationState_Table_ClusterState_ReplicationState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Table_ClusterState_ReplicationState_IsValid(int value);
constexpr Table_ClusterState_ReplicationState Table_ClusterState_ReplicationState_ReplicationState_MIN = Table_ClusterState_ReplicationState_STATE_NOT_KNOWN;
constexpr Table_ClusterState_ReplicationState Table_ClusterState_ReplicationState_ReplicationState_MAX = Table_ClusterState_ReplicationState_READY;
constexpr int Table_ClusterState_ReplicationState_ReplicationState_ARRAYSIZE = Table_ClusterState_ReplicationState_ReplicationState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Table_ClusterState_ReplicationState_descriptor();
template<typename T>
inline const std::string& Table_ClusterState_ReplicationState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Table_ClusterState_ReplicationState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Table_ClusterState_ReplicationState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Table_ClusterState_ReplicationState_descriptor(), enum_t_value);
}
inline bool Table_ClusterState_ReplicationState_Parse(
    const std::string& name, Table_ClusterState_ReplicationState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Table_ClusterState_ReplicationState>(
    Table_ClusterState_ReplicationState_descriptor(), name, value);
}
enum Table_TimestampGranularity : int {
  Table_TimestampGranularity_TIMESTAMP_GRANULARITY_UNSPECIFIED = 0,
  Table_TimestampGranularity_MILLIS = 1,
  Table_TimestampGranularity_Table_TimestampGranularity_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Table_TimestampGranularity_Table_TimestampGranularity_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Table_TimestampGranularity_IsValid(int value);
constexpr Table_TimestampGranularity Table_TimestampGranularity_TimestampGranularity_MIN = Table_TimestampGranularity_TIMESTAMP_GRANULARITY_UNSPECIFIED;
constexpr Table_TimestampGranularity Table_TimestampGranularity_TimestampGranularity_MAX = Table_TimestampGranularity_MILLIS;
constexpr int Table_TimestampGranularity_TimestampGranularity_ARRAYSIZE = Table_TimestampGranularity_TimestampGranularity_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Table_TimestampGranularity_descriptor();
template<typename T>
inline const std::string& Table_TimestampGranularity_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Table_TimestampGranularity>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Table_TimestampGranularity_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Table_TimestampGranularity_descriptor(), enum_t_value);
}
inline bool Table_TimestampGranularity_Parse(
    const std::string& name, Table_TimestampGranularity* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Table_TimestampGranularity>(
    Table_TimestampGranularity_descriptor(), name, value);
}
enum Table_View : int {
  Table_View_VIEW_UNSPECIFIED = 0,
  Table_View_NAME_ONLY = 1,
  Table_View_SCHEMA_VIEW = 2,
  Table_View_REPLICATION_VIEW = 3,
  Table_View_FULL = 4,
  Table_View_Table_View_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Table_View_Table_View_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Table_View_IsValid(int value);
constexpr Table_View Table_View_View_MIN = Table_View_VIEW_UNSPECIFIED;
constexpr Table_View Table_View_View_MAX = Table_View_FULL;
constexpr int Table_View_View_ARRAYSIZE = Table_View_View_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Table_View_descriptor();
template<typename T>
inline const std::string& Table_View_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Table_View>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Table_View_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Table_View_descriptor(), enum_t_value);
}
inline bool Table_View_Parse(
    const std::string& name, Table_View* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Table_View>(
    Table_View_descriptor(), name, value);
}
enum Snapshot_State : int {
  Snapshot_State_STATE_NOT_KNOWN = 0,
  Snapshot_State_READY = 1,
  Snapshot_State_CREATING = 2,
  Snapshot_State_Snapshot_State_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Snapshot_State_Snapshot_State_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Snapshot_State_IsValid(int value);
constexpr Snapshot_State Snapshot_State_State_MIN = Snapshot_State_STATE_NOT_KNOWN;
constexpr Snapshot_State Snapshot_State_State_MAX = Snapshot_State_CREATING;
constexpr int Snapshot_State_State_ARRAYSIZE = Snapshot_State_State_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Snapshot_State_descriptor();
template<typename T>
inline const std::string& Snapshot_State_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Snapshot_State>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Snapshot_State_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Snapshot_State_descriptor(), enum_t_value);
}
inline bool Snapshot_State_Parse(
    const std::string& name, Snapshot_State* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Snapshot_State>(
    Snapshot_State_descriptor(), name, value);
}
// ===================================================================

class Table_ClusterState :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.Table.ClusterState) */ {
 public:
  Table_ClusterState();
  virtual ~Table_ClusterState();

  Table_ClusterState(const Table_ClusterState& from);
  Table_ClusterState(Table_ClusterState&& from) noexcept
    : Table_ClusterState() {
    *this = ::std::move(from);
  }

  inline Table_ClusterState& operator=(const Table_ClusterState& from) {
    CopyFrom(from);
    return *this;
  }
  inline Table_ClusterState& operator=(Table_ClusterState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Table_ClusterState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Table_ClusterState* internal_default_instance() {
    return reinterpret_cast<const Table_ClusterState*>(
               &_Table_ClusterState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Table_ClusterState& a, Table_ClusterState& b) {
    a.Swap(&b);
  }
  inline void Swap(Table_ClusterState* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Table_ClusterState* New() const final {
    return CreateMaybeMessage<Table_ClusterState>(nullptr);
  }

  Table_ClusterState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Table_ClusterState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Table_ClusterState& from);
  void MergeFrom(const Table_ClusterState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Table_ClusterState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.Table.ClusterState";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Table_ClusterState_ReplicationState ReplicationState;
  static constexpr ReplicationState STATE_NOT_KNOWN =
    Table_ClusterState_ReplicationState_STATE_NOT_KNOWN;
  static constexpr ReplicationState INITIALIZING =
    Table_ClusterState_ReplicationState_INITIALIZING;
  static constexpr ReplicationState PLANNED_MAINTENANCE =
    Table_ClusterState_ReplicationState_PLANNED_MAINTENANCE;
  static constexpr ReplicationState UNPLANNED_MAINTENANCE =
    Table_ClusterState_ReplicationState_UNPLANNED_MAINTENANCE;
  static constexpr ReplicationState READY =
    Table_ClusterState_ReplicationState_READY;
  static inline bool ReplicationState_IsValid(int value) {
    return Table_ClusterState_ReplicationState_IsValid(value);
  }
  static constexpr ReplicationState ReplicationState_MIN =
    Table_ClusterState_ReplicationState_ReplicationState_MIN;
  static constexpr ReplicationState ReplicationState_MAX =
    Table_ClusterState_ReplicationState_ReplicationState_MAX;
  static constexpr int ReplicationState_ARRAYSIZE =
    Table_ClusterState_ReplicationState_ReplicationState_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ReplicationState_descriptor() {
    return Table_ClusterState_ReplicationState_descriptor();
  }
  template<typename T>
  static inline const std::string& ReplicationState_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ReplicationState>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ReplicationState_Name.");
    return Table_ClusterState_ReplicationState_Name(enum_t_value);
  }
  static inline bool ReplicationState_Parse(const std::string& name,
      ReplicationState* value) {
    return Table_ClusterState_ReplicationState_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kReplicationStateFieldNumber = 1,
  };
  // .google.bigtable.admin.v2.Table.ClusterState.ReplicationState replication_state = 1;
  void clear_replication_state();
  ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState replication_state() const;
  void set_replication_state(::google::bigtable::admin::v2::Table_ClusterState_ReplicationState value);
  private:
  ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState _internal_replication_state() const;
  void _internal_set_replication_state(::google::bigtable::admin::v2::Table_ClusterState_ReplicationState value);
  public:

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.Table.ClusterState)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  int replication_state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class Table_ClusterStatesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Table_ClusterStatesEntry_DoNotUse, 
    std::string, ::google::bigtable::admin::v2::Table_ClusterState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Table_ClusterStatesEntry_DoNotUse, 
    std::string, ::google::bigtable::admin::v2::Table_ClusterState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Table_ClusterStatesEntry_DoNotUse();
  Table_ClusterStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Table_ClusterStatesEntry_DoNotUse& other);
  static const Table_ClusterStatesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Table_ClusterStatesEntry_DoNotUse*>(&_Table_ClusterStatesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "google.bigtable.admin.v2.Table.ClusterStatesEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class Table_ColumnFamiliesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Table_ColumnFamiliesEntry_DoNotUse, 
    std::string, ::google::bigtable::admin::v2::ColumnFamily,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Table_ColumnFamiliesEntry_DoNotUse, 
    std::string, ::google::bigtable::admin::v2::ColumnFamily,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Table_ColumnFamiliesEntry_DoNotUse();
  Table_ColumnFamiliesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Table_ColumnFamiliesEntry_DoNotUse& other);
  static const Table_ColumnFamiliesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Table_ColumnFamiliesEntry_DoNotUse*>(&_Table_ColumnFamiliesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "google.bigtable.admin.v2.Table.ColumnFamiliesEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class Table :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.Table) */ {
 public:
  Table();
  virtual ~Table();

  Table(const Table& from);
  Table(Table&& from) noexcept
    : Table() {
    *this = ::std::move(from);
  }

  inline Table& operator=(const Table& from) {
    CopyFrom(from);
    return *this;
  }
  inline Table& operator=(Table&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Table& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Table* internal_default_instance() {
    return reinterpret_cast<const Table*>(
               &_Table_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Table& a, Table& b) {
    a.Swap(&b);
  }
  inline void Swap(Table* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Table* New() const final {
    return CreateMaybeMessage<Table>(nullptr);
  }

  Table* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Table>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Table& from);
  void MergeFrom(const Table& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Table* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.Table";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Table_ClusterState ClusterState;

  typedef Table_TimestampGranularity TimestampGranularity;
  static constexpr TimestampGranularity TIMESTAMP_GRANULARITY_UNSPECIFIED =
    Table_TimestampGranularity_TIMESTAMP_GRANULARITY_UNSPECIFIED;
  static constexpr TimestampGranularity MILLIS =
    Table_TimestampGranularity_MILLIS;
  static inline bool TimestampGranularity_IsValid(int value) {
    return Table_TimestampGranularity_IsValid(value);
  }
  static constexpr TimestampGranularity TimestampGranularity_MIN =
    Table_TimestampGranularity_TimestampGranularity_MIN;
  static constexpr TimestampGranularity TimestampGranularity_MAX =
    Table_TimestampGranularity_TimestampGranularity_MAX;
  static constexpr int TimestampGranularity_ARRAYSIZE =
    Table_TimestampGranularity_TimestampGranularity_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  TimestampGranularity_descriptor() {
    return Table_TimestampGranularity_descriptor();
  }
  template<typename T>
  static inline const std::string& TimestampGranularity_Name(T enum_t_value) {
    static_assert(::std::is_same<T, TimestampGranularity>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function TimestampGranularity_Name.");
    return Table_TimestampGranularity_Name(enum_t_value);
  }
  static inline bool TimestampGranularity_Parse(const std::string& name,
      TimestampGranularity* value) {
    return Table_TimestampGranularity_Parse(name, value);
  }

  typedef Table_View View;
  static constexpr View VIEW_UNSPECIFIED =
    Table_View_VIEW_UNSPECIFIED;
  static constexpr View NAME_ONLY =
    Table_View_NAME_ONLY;
  static constexpr View SCHEMA_VIEW =
    Table_View_SCHEMA_VIEW;
  static constexpr View REPLICATION_VIEW =
    Table_View_REPLICATION_VIEW;
  static constexpr View FULL =
    Table_View_FULL;
  static inline bool View_IsValid(int value) {
    return Table_View_IsValid(value);
  }
  static constexpr View View_MIN =
    Table_View_View_MIN;
  static constexpr View View_MAX =
    Table_View_View_MAX;
  static constexpr int View_ARRAYSIZE =
    Table_View_View_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  View_descriptor() {
    return Table_View_descriptor();
  }
  template<typename T>
  static inline const std::string& View_Name(T enum_t_value) {
    static_assert(::std::is_same<T, View>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function View_Name.");
    return Table_View_Name(enum_t_value);
  }
  static inline bool View_Parse(const std::string& name,
      View* value) {
    return Table_View_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kClusterStatesFieldNumber = 2,
    kColumnFamiliesFieldNumber = 3,
    kNameFieldNumber = 1,
    kGranularityFieldNumber = 4,
  };
  // map<string, .google.bigtable.admin.v2.Table.ClusterState> cluster_states = 2;
  int cluster_states_size() const;
  private:
  int _internal_cluster_states_size() const;
  public:
  void clear_cluster_states();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >&
      _internal_cluster_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >*
      _internal_mutable_cluster_states();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >&
      cluster_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >*
      mutable_cluster_states();

  // map<string, .google.bigtable.admin.v2.ColumnFamily> column_families = 3;
  int column_families_size() const;
  private:
  int _internal_column_families_size() const;
  public:
  void clear_column_families();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >&
      _internal_column_families() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >*
      _internal_mutable_column_families();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >&
      column_families() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >*
      mutable_column_families();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .google.bigtable.admin.v2.Table.TimestampGranularity granularity = 4;
  void clear_granularity();
  ::google::bigtable::admin::v2::Table_TimestampGranularity granularity() const;
  void set_granularity(::google::bigtable::admin::v2::Table_TimestampGranularity value);
  private:
  ::google::bigtable::admin::v2::Table_TimestampGranularity _internal_granularity() const;
  void _internal_set_granularity(::google::bigtable::admin::v2::Table_TimestampGranularity value);
  public:

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.Table)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Table_ClusterStatesEntry_DoNotUse,
      std::string, ::google::bigtable::admin::v2::Table_ClusterState,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > cluster_states_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Table_ColumnFamiliesEntry_DoNotUse,
      std::string, ::google::bigtable::admin::v2::ColumnFamily,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > column_families_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int granularity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class ColumnFamily :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.ColumnFamily) */ {
 public:
  ColumnFamily();
  virtual ~ColumnFamily();

  ColumnFamily(const ColumnFamily& from);
  ColumnFamily(ColumnFamily&& from) noexcept
    : ColumnFamily() {
    *this = ::std::move(from);
  }

  inline ColumnFamily& operator=(const ColumnFamily& from) {
    CopyFrom(from);
    return *this;
  }
  inline ColumnFamily& operator=(ColumnFamily&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ColumnFamily& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ColumnFamily* internal_default_instance() {
    return reinterpret_cast<const ColumnFamily*>(
               &_ColumnFamily_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ColumnFamily& a, ColumnFamily& b) {
    a.Swap(&b);
  }
  inline void Swap(ColumnFamily* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ColumnFamily* New() const final {
    return CreateMaybeMessage<ColumnFamily>(nullptr);
  }

  ColumnFamily* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ColumnFamily>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ColumnFamily& from);
  void MergeFrom(const ColumnFamily& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ColumnFamily* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.ColumnFamily";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGcRuleFieldNumber = 1,
  };
  // .google.bigtable.admin.v2.GcRule gc_rule = 1;
  bool has_gc_rule() const;
  private:
  bool _internal_has_gc_rule() const;
  public:
  void clear_gc_rule();
  const ::google::bigtable::admin::v2::GcRule& gc_rule() const;
  ::google::bigtable::admin::v2::GcRule* release_gc_rule();
  ::google::bigtable::admin::v2::GcRule* mutable_gc_rule();
  void set_allocated_gc_rule(::google::bigtable::admin::v2::GcRule* gc_rule);
  private:
  const ::google::bigtable::admin::v2::GcRule& _internal_gc_rule() const;
  ::google::bigtable::admin::v2::GcRule* _internal_mutable_gc_rule();
  public:

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.ColumnFamily)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::bigtable::admin::v2::GcRule* gc_rule_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class GcRule_Intersection :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.GcRule.Intersection) */ {
 public:
  GcRule_Intersection();
  virtual ~GcRule_Intersection();

  GcRule_Intersection(const GcRule_Intersection& from);
  GcRule_Intersection(GcRule_Intersection&& from) noexcept
    : GcRule_Intersection() {
    *this = ::std::move(from);
  }

  inline GcRule_Intersection& operator=(const GcRule_Intersection& from) {
    CopyFrom(from);
    return *this;
  }
  inline GcRule_Intersection& operator=(GcRule_Intersection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GcRule_Intersection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GcRule_Intersection* internal_default_instance() {
    return reinterpret_cast<const GcRule_Intersection*>(
               &_GcRule_Intersection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GcRule_Intersection& a, GcRule_Intersection& b) {
    a.Swap(&b);
  }
  inline void Swap(GcRule_Intersection* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GcRule_Intersection* New() const final {
    return CreateMaybeMessage<GcRule_Intersection>(nullptr);
  }

  GcRule_Intersection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GcRule_Intersection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GcRule_Intersection& from);
  void MergeFrom(const GcRule_Intersection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GcRule_Intersection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.GcRule.Intersection";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRulesFieldNumber = 1,
  };
  // repeated .google.bigtable.admin.v2.GcRule rules = 1;
  int rules_size() const;
  private:
  int _internal_rules_size() const;
  public:
  void clear_rules();
  ::google::bigtable::admin::v2::GcRule* mutable_rules(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >*
      mutable_rules();
  private:
  const ::google::bigtable::admin::v2::GcRule& _internal_rules(int index) const;
  ::google::bigtable::admin::v2::GcRule* _internal_add_rules();
  public:
  const ::google::bigtable::admin::v2::GcRule& rules(int index) const;
  ::google::bigtable::admin::v2::GcRule* add_rules();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >&
      rules() const;

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.GcRule.Intersection)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule > rules_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class GcRule_Union :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.GcRule.Union) */ {
 public:
  GcRule_Union();
  virtual ~GcRule_Union();

  GcRule_Union(const GcRule_Union& from);
  GcRule_Union(GcRule_Union&& from) noexcept
    : GcRule_Union() {
    *this = ::std::move(from);
  }

  inline GcRule_Union& operator=(const GcRule_Union& from) {
    CopyFrom(from);
    return *this;
  }
  inline GcRule_Union& operator=(GcRule_Union&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GcRule_Union& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GcRule_Union* internal_default_instance() {
    return reinterpret_cast<const GcRule_Union*>(
               &_GcRule_Union_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GcRule_Union& a, GcRule_Union& b) {
    a.Swap(&b);
  }
  inline void Swap(GcRule_Union* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GcRule_Union* New() const final {
    return CreateMaybeMessage<GcRule_Union>(nullptr);
  }

  GcRule_Union* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GcRule_Union>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GcRule_Union& from);
  void MergeFrom(const GcRule_Union& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GcRule_Union* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.GcRule.Union";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRulesFieldNumber = 1,
  };
  // repeated .google.bigtable.admin.v2.GcRule rules = 1;
  int rules_size() const;
  private:
  int _internal_rules_size() const;
  public:
  void clear_rules();
  ::google::bigtable::admin::v2::GcRule* mutable_rules(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >*
      mutable_rules();
  private:
  const ::google::bigtable::admin::v2::GcRule& _internal_rules(int index) const;
  ::google::bigtable::admin::v2::GcRule* _internal_add_rules();
  public:
  const ::google::bigtable::admin::v2::GcRule& rules(int index) const;
  ::google::bigtable::admin::v2::GcRule* add_rules();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >&
      rules() const;

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.GcRule.Union)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule > rules_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class GcRule :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.GcRule) */ {
 public:
  GcRule();
  virtual ~GcRule();

  GcRule(const GcRule& from);
  GcRule(GcRule&& from) noexcept
    : GcRule() {
    *this = ::std::move(from);
  }

  inline GcRule& operator=(const GcRule& from) {
    CopyFrom(from);
    return *this;
  }
  inline GcRule& operator=(GcRule&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GcRule& default_instance();

  enum RuleCase {
    kMaxNumVersions = 1,
    kMaxAge = 2,
    kIntersection = 3,
    kUnion = 4,
    RULE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GcRule* internal_default_instance() {
    return reinterpret_cast<const GcRule*>(
               &_GcRule_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GcRule& a, GcRule& b) {
    a.Swap(&b);
  }
  inline void Swap(GcRule* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GcRule* New() const final {
    return CreateMaybeMessage<GcRule>(nullptr);
  }

  GcRule* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GcRule>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GcRule& from);
  void MergeFrom(const GcRule& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GcRule* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.GcRule";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef GcRule_Intersection Intersection;
  typedef GcRule_Union Union;

  // accessors -------------------------------------------------------

  enum : int {
    kMaxNumVersionsFieldNumber = 1,
    kMaxAgeFieldNumber = 2,
    kIntersectionFieldNumber = 3,
    kUnionFieldNumber = 4,
  };
  // int32 max_num_versions = 1;
  private:
  bool _internal_has_max_num_versions() const;
  public:
  void clear_max_num_versions();
  ::PROTOBUF_NAMESPACE_ID::int32 max_num_versions() const;
  void set_max_num_versions(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_num_versions() const;
  void _internal_set_max_num_versions(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .google.protobuf.Duration max_age = 2;
  bool has_max_age() const;
  private:
  bool _internal_has_max_age() const;
  public:
  void clear_max_age();
  const PROTOBUF_NAMESPACE_ID::Duration& max_age() const;
  PROTOBUF_NAMESPACE_ID::Duration* release_max_age();
  PROTOBUF_NAMESPACE_ID::Duration* mutable_max_age();
  void set_allocated_max_age(PROTOBUF_NAMESPACE_ID::Duration* max_age);
  private:
  const PROTOBUF_NAMESPACE_ID::Duration& _internal_max_age() const;
  PROTOBUF_NAMESPACE_ID::Duration* _internal_mutable_max_age();
  public:

  // .google.bigtable.admin.v2.GcRule.Intersection intersection = 3;
  bool has_intersection() const;
  private:
  bool _internal_has_intersection() const;
  public:
  void clear_intersection();
  const ::google::bigtable::admin::v2::GcRule_Intersection& intersection() const;
  ::google::bigtable::admin::v2::GcRule_Intersection* release_intersection();
  ::google::bigtable::admin::v2::GcRule_Intersection* mutable_intersection();
  void set_allocated_intersection(::google::bigtable::admin::v2::GcRule_Intersection* intersection);
  private:
  const ::google::bigtable::admin::v2::GcRule_Intersection& _internal_intersection() const;
  ::google::bigtable::admin::v2::GcRule_Intersection* _internal_mutable_intersection();
  public:

  // .google.bigtable.admin.v2.GcRule.Union union = 4;
  bool has_union_() const;
  private:
  bool _internal_has_union_() const;
  public:
  void clear_union_();
  const ::google::bigtable::admin::v2::GcRule_Union& union_() const;
  ::google::bigtable::admin::v2::GcRule_Union* release_union_();
  ::google::bigtable::admin::v2::GcRule_Union* mutable_union_();
  void set_allocated_union_(::google::bigtable::admin::v2::GcRule_Union* union_);
  private:
  const ::google::bigtable::admin::v2::GcRule_Union& _internal_union_() const;
  ::google::bigtable::admin::v2::GcRule_Union* _internal_mutable_union_();
  public:

  void clear_rule();
  RuleCase rule_case() const;
  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.GcRule)
 private:
  class _Internal;
  void set_has_max_num_versions();
  void set_has_max_age();
  void set_has_intersection();
  void set_has_union_();

  inline bool has_rule() const;
  inline void clear_has_rule();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  union RuleUnion {
    RuleUnion() {}
    ::PROTOBUF_NAMESPACE_ID::int32 max_num_versions_;
    PROTOBUF_NAMESPACE_ID::Duration* max_age_;
    ::google::bigtable::admin::v2::GcRule_Intersection* intersection_;
    ::google::bigtable::admin::v2::GcRule_Union* union__;
  } rule_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// -------------------------------------------------------------------

class Snapshot :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.bigtable.admin.v2.Snapshot) */ {
 public:
  Snapshot();
  virtual ~Snapshot();

  Snapshot(const Snapshot& from);
  Snapshot(Snapshot&& from) noexcept
    : Snapshot() {
    *this = ::std::move(from);
  }

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline Snapshot& operator=(Snapshot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Snapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Snapshot* internal_default_instance() {
    return reinterpret_cast<const Snapshot*>(
               &_Snapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(Snapshot& a, Snapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(Snapshot* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Snapshot* New() const final {
    return CreateMaybeMessage<Snapshot>(nullptr);
  }

  Snapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Snapshot>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Snapshot& from);
  void MergeFrom(const Snapshot& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Snapshot* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.bigtable.admin.v2.Snapshot";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto);
    return ::descriptor_table_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Snapshot_State State;
  static constexpr State STATE_NOT_KNOWN =
    Snapshot_State_STATE_NOT_KNOWN;
  static constexpr State READY =
    Snapshot_State_READY;
  static constexpr State CREATING =
    Snapshot_State_CREATING;
  static inline bool State_IsValid(int value) {
    return Snapshot_State_IsValid(value);
  }
  static constexpr State State_MIN =
    Snapshot_State_State_MIN;
  static constexpr State State_MAX =
    Snapshot_State_State_MAX;
  static constexpr int State_ARRAYSIZE =
    Snapshot_State_State_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  State_descriptor() {
    return Snapshot_State_descriptor();
  }
  template<typename T>
  static inline const std::string& State_Name(T enum_t_value) {
    static_assert(::std::is_same<T, State>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function State_Name.");
    return Snapshot_State_Name(enum_t_value);
  }
  static inline bool State_Parse(const std::string& name,
      State* value) {
    return Snapshot_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDescriptionFieldNumber = 7,
    kSourceTableFieldNumber = 2,
    kCreateTimeFieldNumber = 4,
    kDeleteTimeFieldNumber = 5,
    kDataSizeBytesFieldNumber = 3,
    kStateFieldNumber = 6,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string description = 7;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // .google.bigtable.admin.v2.Table source_table = 2;
  bool has_source_table() const;
  private:
  bool _internal_has_source_table() const;
  public:
  void clear_source_table();
  const ::google::bigtable::admin::v2::Table& source_table() const;
  ::google::bigtable::admin::v2::Table* release_source_table();
  ::google::bigtable::admin::v2::Table* mutable_source_table();
  void set_allocated_source_table(::google::bigtable::admin::v2::Table* source_table);
  private:
  const ::google::bigtable::admin::v2::Table& _internal_source_table() const;
  ::google::bigtable::admin::v2::Table* _internal_mutable_source_table();
  public:

  // .google.protobuf.Timestamp create_time = 4;
  bool has_create_time() const;
  private:
  bool _internal_has_create_time() const;
  public:
  void clear_create_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& create_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_create_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_create_time();
  void set_allocated_create_time(PROTOBUF_NAMESPACE_ID::Timestamp* create_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_create_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_create_time();
  public:

  // .google.protobuf.Timestamp delete_time = 5;
  bool has_delete_time() const;
  private:
  bool _internal_has_delete_time() const;
  public:
  void clear_delete_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& delete_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_delete_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_delete_time();
  void set_allocated_delete_time(PROTOBUF_NAMESPACE_ID::Timestamp* delete_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_delete_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_delete_time();
  public:

  // int64 data_size_bytes = 3;
  void clear_data_size_bytes();
  ::PROTOBUF_NAMESPACE_ID::int64 data_size_bytes() const;
  void set_data_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_data_size_bytes() const;
  void _internal_set_data_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // .google.bigtable.admin.v2.Snapshot.State state = 6;
  void clear_state();
  ::google::bigtable::admin::v2::Snapshot_State state() const;
  void set_state(::google::bigtable::admin::v2::Snapshot_State value);
  private:
  ::google::bigtable::admin::v2::Snapshot_State _internal_state() const;
  void _internal_set_state(::google::bigtable::admin::v2::Snapshot_State value);
  public:

  // @@protoc_insertion_point(class_scope:google.bigtable.admin.v2.Snapshot)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::google::bigtable::admin::v2::Table* source_table_;
  PROTOBUF_NAMESPACE_ID::Timestamp* create_time_;
  PROTOBUF_NAMESPACE_ID::Timestamp* delete_time_;
  ::PROTOBUF_NAMESPACE_ID::int64 data_size_bytes_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Table_ClusterState

// .google.bigtable.admin.v2.Table.ClusterState.ReplicationState replication_state = 1;
inline void Table_ClusterState::clear_replication_state() {
  replication_state_ = 0;
}
inline ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState Table_ClusterState::_internal_replication_state() const {
  return static_cast< ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState >(replication_state_);
}
inline ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState Table_ClusterState::replication_state() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Table.ClusterState.replication_state)
  return _internal_replication_state();
}
inline void Table_ClusterState::_internal_set_replication_state(::google::bigtable::admin::v2::Table_ClusterState_ReplicationState value) {
  
  replication_state_ = value;
}
inline void Table_ClusterState::set_replication_state(::google::bigtable::admin::v2::Table_ClusterState_ReplicationState value) {
  _internal_set_replication_state(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Table.ClusterState.replication_state)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Table

// string name = 1;
inline void Table::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Table::name() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Table.name)
  return _internal_name();
}
inline void Table::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Table.name)
}
inline std::string* Table::mutable_name() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Table.name)
  return _internal_mutable_name();
}
inline const std::string& Table::_internal_name() const {
  return name_.GetNoArena();
}
inline void Table::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Table::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.bigtable.admin.v2.Table.name)
}
inline void Table::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.bigtable.admin.v2.Table.name)
}
inline void Table::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.bigtable.admin.v2.Table.name)
}
inline std::string* Table::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Table::release_name() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Table.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Table::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Table.name)
}

// map<string, .google.bigtable.admin.v2.Table.ClusterState> cluster_states = 2;
inline int Table::_internal_cluster_states_size() const {
  return cluster_states_.size();
}
inline int Table::cluster_states_size() const {
  return _internal_cluster_states_size();
}
inline void Table::clear_cluster_states() {
  cluster_states_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >&
Table::_internal_cluster_states() const {
  return cluster_states_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >&
Table::cluster_states() const {
  // @@protoc_insertion_point(field_map:google.bigtable.admin.v2.Table.cluster_states)
  return _internal_cluster_states();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >*
Table::_internal_mutable_cluster_states() {
  return cluster_states_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::Table_ClusterState >*
Table::mutable_cluster_states() {
  // @@protoc_insertion_point(field_mutable_map:google.bigtable.admin.v2.Table.cluster_states)
  return _internal_mutable_cluster_states();
}

// map<string, .google.bigtable.admin.v2.ColumnFamily> column_families = 3;
inline int Table::_internal_column_families_size() const {
  return column_families_.size();
}
inline int Table::column_families_size() const {
  return _internal_column_families_size();
}
inline void Table::clear_column_families() {
  column_families_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >&
Table::_internal_column_families() const {
  return column_families_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >&
Table::column_families() const {
  // @@protoc_insertion_point(field_map:google.bigtable.admin.v2.Table.column_families)
  return _internal_column_families();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >*
Table::_internal_mutable_column_families() {
  return column_families_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::google::bigtable::admin::v2::ColumnFamily >*
Table::mutable_column_families() {
  // @@protoc_insertion_point(field_mutable_map:google.bigtable.admin.v2.Table.column_families)
  return _internal_mutable_column_families();
}

// .google.bigtable.admin.v2.Table.TimestampGranularity granularity = 4;
inline void Table::clear_granularity() {
  granularity_ = 0;
}
inline ::google::bigtable::admin::v2::Table_TimestampGranularity Table::_internal_granularity() const {
  return static_cast< ::google::bigtable::admin::v2::Table_TimestampGranularity >(granularity_);
}
inline ::google::bigtable::admin::v2::Table_TimestampGranularity Table::granularity() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Table.granularity)
  return _internal_granularity();
}
inline void Table::_internal_set_granularity(::google::bigtable::admin::v2::Table_TimestampGranularity value) {
  
  granularity_ = value;
}
inline void Table::set_granularity(::google::bigtable::admin::v2::Table_TimestampGranularity value) {
  _internal_set_granularity(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Table.granularity)
}

// -------------------------------------------------------------------

// ColumnFamily

// .google.bigtable.admin.v2.GcRule gc_rule = 1;
inline bool ColumnFamily::_internal_has_gc_rule() const {
  return this != internal_default_instance() && gc_rule_ != nullptr;
}
inline bool ColumnFamily::has_gc_rule() const {
  return _internal_has_gc_rule();
}
inline void ColumnFamily::clear_gc_rule() {
  if (GetArenaNoVirtual() == nullptr && gc_rule_ != nullptr) {
    delete gc_rule_;
  }
  gc_rule_ = nullptr;
}
inline const ::google::bigtable::admin::v2::GcRule& ColumnFamily::_internal_gc_rule() const {
  const ::google::bigtable::admin::v2::GcRule* p = gc_rule_;
  return p != nullptr ? *p : *reinterpret_cast<const ::google::bigtable::admin::v2::GcRule*>(
      &::google::bigtable::admin::v2::_GcRule_default_instance_);
}
inline const ::google::bigtable::admin::v2::GcRule& ColumnFamily::gc_rule() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.ColumnFamily.gc_rule)
  return _internal_gc_rule();
}
inline ::google::bigtable::admin::v2::GcRule* ColumnFamily::release_gc_rule() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.ColumnFamily.gc_rule)
  
  ::google::bigtable::admin::v2::GcRule* temp = gc_rule_;
  gc_rule_ = nullptr;
  return temp;
}
inline ::google::bigtable::admin::v2::GcRule* ColumnFamily::_internal_mutable_gc_rule() {
  
  if (gc_rule_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::bigtable::admin::v2::GcRule>(GetArenaNoVirtual());
    gc_rule_ = p;
  }
  return gc_rule_;
}
inline ::google::bigtable::admin::v2::GcRule* ColumnFamily::mutable_gc_rule() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.ColumnFamily.gc_rule)
  return _internal_mutable_gc_rule();
}
inline void ColumnFamily::set_allocated_gc_rule(::google::bigtable::admin::v2::GcRule* gc_rule) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete gc_rule_;
  }
  if (gc_rule) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      gc_rule = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gc_rule, submessage_arena);
    }
    
  } else {
    
  }
  gc_rule_ = gc_rule;
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.ColumnFamily.gc_rule)
}

// -------------------------------------------------------------------

// GcRule_Intersection

// repeated .google.bigtable.admin.v2.GcRule rules = 1;
inline int GcRule_Intersection::_internal_rules_size() const {
  return rules_.size();
}
inline int GcRule_Intersection::rules_size() const {
  return _internal_rules_size();
}
inline void GcRule_Intersection::clear_rules() {
  rules_.Clear();
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Intersection::mutable_rules(int index) {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.GcRule.Intersection.rules)
  return rules_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >*
GcRule_Intersection::mutable_rules() {
  // @@protoc_insertion_point(field_mutable_list:google.bigtable.admin.v2.GcRule.Intersection.rules)
  return &rules_;
}
inline const ::google::bigtable::admin::v2::GcRule& GcRule_Intersection::_internal_rules(int index) const {
  return rules_.Get(index);
}
inline const ::google::bigtable::admin::v2::GcRule& GcRule_Intersection::rules(int index) const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.Intersection.rules)
  return _internal_rules(index);
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Intersection::_internal_add_rules() {
  return rules_.Add();
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Intersection::add_rules() {
  // @@protoc_insertion_point(field_add:google.bigtable.admin.v2.GcRule.Intersection.rules)
  return _internal_add_rules();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >&
GcRule_Intersection::rules() const {
  // @@protoc_insertion_point(field_list:google.bigtable.admin.v2.GcRule.Intersection.rules)
  return rules_;
}

// -------------------------------------------------------------------

// GcRule_Union

// repeated .google.bigtable.admin.v2.GcRule rules = 1;
inline int GcRule_Union::_internal_rules_size() const {
  return rules_.size();
}
inline int GcRule_Union::rules_size() const {
  return _internal_rules_size();
}
inline void GcRule_Union::clear_rules() {
  rules_.Clear();
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Union::mutable_rules(int index) {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.GcRule.Union.rules)
  return rules_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >*
GcRule_Union::mutable_rules() {
  // @@protoc_insertion_point(field_mutable_list:google.bigtable.admin.v2.GcRule.Union.rules)
  return &rules_;
}
inline const ::google::bigtable::admin::v2::GcRule& GcRule_Union::_internal_rules(int index) const {
  return rules_.Get(index);
}
inline const ::google::bigtable::admin::v2::GcRule& GcRule_Union::rules(int index) const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.Union.rules)
  return _internal_rules(index);
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Union::_internal_add_rules() {
  return rules_.Add();
}
inline ::google::bigtable::admin::v2::GcRule* GcRule_Union::add_rules() {
  // @@protoc_insertion_point(field_add:google.bigtable.admin.v2.GcRule.Union.rules)
  return _internal_add_rules();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::bigtable::admin::v2::GcRule >&
GcRule_Union::rules() const {
  // @@protoc_insertion_point(field_list:google.bigtable.admin.v2.GcRule.Union.rules)
  return rules_;
}

// -------------------------------------------------------------------

// GcRule

// int32 max_num_versions = 1;
inline bool GcRule::_internal_has_max_num_versions() const {
  return rule_case() == kMaxNumVersions;
}
inline void GcRule::set_has_max_num_versions() {
  _oneof_case_[0] = kMaxNumVersions;
}
inline void GcRule::clear_max_num_versions() {
  if (_internal_has_max_num_versions()) {
    rule_.max_num_versions_ = 0;
    clear_has_rule();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GcRule::_internal_max_num_versions() const {
  if (_internal_has_max_num_versions()) {
    return rule_.max_num_versions_;
  }
  return 0;
}
inline void GcRule::_internal_set_max_num_versions(::PROTOBUF_NAMESPACE_ID::int32 value) {
  if (!_internal_has_max_num_versions()) {
    clear_rule();
    set_has_max_num_versions();
  }
  rule_.max_num_versions_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GcRule::max_num_versions() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.max_num_versions)
  return _internal_max_num_versions();
}
inline void GcRule::set_max_num_versions(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_num_versions(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.GcRule.max_num_versions)
}

// .google.protobuf.Duration max_age = 2;
inline bool GcRule::_internal_has_max_age() const {
  return rule_case() == kMaxAge;
}
inline bool GcRule::has_max_age() const {
  return _internal_has_max_age();
}
inline void GcRule::set_has_max_age() {
  _oneof_case_[0] = kMaxAge;
}
inline PROTOBUF_NAMESPACE_ID::Duration* GcRule::release_max_age() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.GcRule.max_age)
  if (has_max_age()) {
    clear_has_rule();
      PROTOBUF_NAMESPACE_ID::Duration* temp = rule_.max_age_;
    rule_.max_age_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const PROTOBUF_NAMESPACE_ID::Duration& GcRule::_internal_max_age() const {
  return _internal_has_max_age()
      ? *rule_.max_age_
      : *reinterpret_cast< PROTOBUF_NAMESPACE_ID::Duration*>(&PROTOBUF_NAMESPACE_ID::_Duration_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Duration& GcRule::max_age() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.max_age)
  return _internal_max_age();
}
inline PROTOBUF_NAMESPACE_ID::Duration* GcRule::_internal_mutable_max_age() {
  if (!_internal_has_max_age()) {
    clear_rule();
    set_has_max_age();
    rule_.max_age_ = CreateMaybeMessage< PROTOBUF_NAMESPACE_ID::Duration >(
        GetArenaNoVirtual());
  }
  return rule_.max_age_;
}
inline PROTOBUF_NAMESPACE_ID::Duration* GcRule::mutable_max_age() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.GcRule.max_age)
  return _internal_mutable_max_age();
}

// .google.bigtable.admin.v2.GcRule.Intersection intersection = 3;
inline bool GcRule::_internal_has_intersection() const {
  return rule_case() == kIntersection;
}
inline bool GcRule::has_intersection() const {
  return _internal_has_intersection();
}
inline void GcRule::set_has_intersection() {
  _oneof_case_[0] = kIntersection;
}
inline void GcRule::clear_intersection() {
  if (_internal_has_intersection()) {
    delete rule_.intersection_;
    clear_has_rule();
  }
}
inline ::google::bigtable::admin::v2::GcRule_Intersection* GcRule::release_intersection() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.GcRule.intersection)
  if (has_intersection()) {
    clear_has_rule();
      ::google::bigtable::admin::v2::GcRule_Intersection* temp = rule_.intersection_;
    rule_.intersection_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::google::bigtable::admin::v2::GcRule_Intersection& GcRule::_internal_intersection() const {
  return _internal_has_intersection()
      ? *rule_.intersection_
      : *reinterpret_cast< ::google::bigtable::admin::v2::GcRule_Intersection*>(&::google::bigtable::admin::v2::_GcRule_Intersection_default_instance_);
}
inline const ::google::bigtable::admin::v2::GcRule_Intersection& GcRule::intersection() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.intersection)
  return _internal_intersection();
}
inline ::google::bigtable::admin::v2::GcRule_Intersection* GcRule::_internal_mutable_intersection() {
  if (!_internal_has_intersection()) {
    clear_rule();
    set_has_intersection();
    rule_.intersection_ = CreateMaybeMessage< ::google::bigtable::admin::v2::GcRule_Intersection >(
        GetArenaNoVirtual());
  }
  return rule_.intersection_;
}
inline ::google::bigtable::admin::v2::GcRule_Intersection* GcRule::mutable_intersection() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.GcRule.intersection)
  return _internal_mutable_intersection();
}

// .google.bigtable.admin.v2.GcRule.Union union = 4;
inline bool GcRule::_internal_has_union_() const {
  return rule_case() == kUnion;
}
inline bool GcRule::has_union_() const {
  return _internal_has_union_();
}
inline void GcRule::set_has_union_() {
  _oneof_case_[0] = kUnion;
}
inline void GcRule::clear_union_() {
  if (_internal_has_union_()) {
    delete rule_.union__;
    clear_has_rule();
  }
}
inline ::google::bigtable::admin::v2::GcRule_Union* GcRule::release_union_() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.GcRule.union)
  if (has_union_()) {
    clear_has_rule();
      ::google::bigtable::admin::v2::GcRule_Union* temp = rule_.union__;
    rule_.union__ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::google::bigtable::admin::v2::GcRule_Union& GcRule::_internal_union_() const {
  return _internal_has_union_()
      ? *rule_.union__
      : *reinterpret_cast< ::google::bigtable::admin::v2::GcRule_Union*>(&::google::bigtable::admin::v2::_GcRule_Union_default_instance_);
}
inline const ::google::bigtable::admin::v2::GcRule_Union& GcRule::union_() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.GcRule.union)
  return _internal_union_();
}
inline ::google::bigtable::admin::v2::GcRule_Union* GcRule::_internal_mutable_union_() {
  if (!_internal_has_union_()) {
    clear_rule();
    set_has_union_();
    rule_.union__ = CreateMaybeMessage< ::google::bigtable::admin::v2::GcRule_Union >(
        GetArenaNoVirtual());
  }
  return rule_.union__;
}
inline ::google::bigtable::admin::v2::GcRule_Union* GcRule::mutable_union_() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.GcRule.union)
  return _internal_mutable_union_();
}

inline bool GcRule::has_rule() const {
  return rule_case() != RULE_NOT_SET;
}
inline void GcRule::clear_has_rule() {
  _oneof_case_[0] = RULE_NOT_SET;
}
inline GcRule::RuleCase GcRule::rule_case() const {
  return GcRule::RuleCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Snapshot

// string name = 1;
inline void Snapshot::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Snapshot::name() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.name)
  return _internal_name();
}
inline void Snapshot::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Snapshot.name)
}
inline std::string* Snapshot::mutable_name() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Snapshot.name)
  return _internal_mutable_name();
}
inline const std::string& Snapshot::_internal_name() const {
  return name_.GetNoArena();
}
inline void Snapshot::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Snapshot::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.bigtable.admin.v2.Snapshot.name)
}
inline void Snapshot::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.bigtable.admin.v2.Snapshot.name)
}
inline void Snapshot::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.bigtable.admin.v2.Snapshot.name)
}
inline std::string* Snapshot::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Snapshot::release_name() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Snapshot.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Snapshot::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Snapshot.name)
}

// .google.bigtable.admin.v2.Table source_table = 2;
inline bool Snapshot::_internal_has_source_table() const {
  return this != internal_default_instance() && source_table_ != nullptr;
}
inline bool Snapshot::has_source_table() const {
  return _internal_has_source_table();
}
inline void Snapshot::clear_source_table() {
  if (GetArenaNoVirtual() == nullptr && source_table_ != nullptr) {
    delete source_table_;
  }
  source_table_ = nullptr;
}
inline const ::google::bigtable::admin::v2::Table& Snapshot::_internal_source_table() const {
  const ::google::bigtable::admin::v2::Table* p = source_table_;
  return p != nullptr ? *p : *reinterpret_cast<const ::google::bigtable::admin::v2::Table*>(
      &::google::bigtable::admin::v2::_Table_default_instance_);
}
inline const ::google::bigtable::admin::v2::Table& Snapshot::source_table() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.source_table)
  return _internal_source_table();
}
inline ::google::bigtable::admin::v2::Table* Snapshot::release_source_table() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Snapshot.source_table)
  
  ::google::bigtable::admin::v2::Table* temp = source_table_;
  source_table_ = nullptr;
  return temp;
}
inline ::google::bigtable::admin::v2::Table* Snapshot::_internal_mutable_source_table() {
  
  if (source_table_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::bigtable::admin::v2::Table>(GetArenaNoVirtual());
    source_table_ = p;
  }
  return source_table_;
}
inline ::google::bigtable::admin::v2::Table* Snapshot::mutable_source_table() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Snapshot.source_table)
  return _internal_mutable_source_table();
}
inline void Snapshot::set_allocated_source_table(::google::bigtable::admin::v2::Table* source_table) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete source_table_;
  }
  if (source_table) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      source_table = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, source_table, submessage_arena);
    }
    
  } else {
    
  }
  source_table_ = source_table;
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Snapshot.source_table)
}

// int64 data_size_bytes = 3;
inline void Snapshot::clear_data_size_bytes() {
  data_size_bytes_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Snapshot::_internal_data_size_bytes() const {
  return data_size_bytes_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Snapshot::data_size_bytes() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.data_size_bytes)
  return _internal_data_size_bytes();
}
inline void Snapshot::_internal_set_data_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  data_size_bytes_ = value;
}
inline void Snapshot::set_data_size_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_data_size_bytes(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Snapshot.data_size_bytes)
}

// .google.protobuf.Timestamp create_time = 4;
inline bool Snapshot::_internal_has_create_time() const {
  return this != internal_default_instance() && create_time_ != nullptr;
}
inline bool Snapshot::has_create_time() const {
  return _internal_has_create_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Snapshot::_internal_create_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = create_time_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Snapshot::create_time() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.create_time)
  return _internal_create_time();
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::release_create_time() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Snapshot.create_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = create_time_;
  create_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::_internal_mutable_create_time() {
  
  if (create_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaNoVirtual());
    create_time_ = p;
  }
  return create_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::mutable_create_time() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Snapshot.create_time)
  return _internal_mutable_create_time();
}
inline void Snapshot::set_allocated_create_time(PROTOBUF_NAMESPACE_ID::Timestamp* create_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(create_time_);
  }
  if (create_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(create_time)->GetArena();
    if (message_arena != submessage_arena) {
      create_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, create_time, submessage_arena);
    }
    
  } else {
    
  }
  create_time_ = create_time;
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Snapshot.create_time)
}

// .google.protobuf.Timestamp delete_time = 5;
inline bool Snapshot::_internal_has_delete_time() const {
  return this != internal_default_instance() && delete_time_ != nullptr;
}
inline bool Snapshot::has_delete_time() const {
  return _internal_has_delete_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Snapshot::_internal_delete_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = delete_time_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Snapshot::delete_time() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.delete_time)
  return _internal_delete_time();
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::release_delete_time() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Snapshot.delete_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = delete_time_;
  delete_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::_internal_mutable_delete_time() {
  
  if (delete_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaNoVirtual());
    delete_time_ = p;
  }
  return delete_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Snapshot::mutable_delete_time() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Snapshot.delete_time)
  return _internal_mutable_delete_time();
}
inline void Snapshot::set_allocated_delete_time(PROTOBUF_NAMESPACE_ID::Timestamp* delete_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(delete_time_);
  }
  if (delete_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(delete_time)->GetArena();
    if (message_arena != submessage_arena) {
      delete_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, delete_time, submessage_arena);
    }
    
  } else {
    
  }
  delete_time_ = delete_time;
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Snapshot.delete_time)
}

// .google.bigtable.admin.v2.Snapshot.State state = 6;
inline void Snapshot::clear_state() {
  state_ = 0;
}
inline ::google::bigtable::admin::v2::Snapshot_State Snapshot::_internal_state() const {
  return static_cast< ::google::bigtable::admin::v2::Snapshot_State >(state_);
}
inline ::google::bigtable::admin::v2::Snapshot_State Snapshot::state() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.state)
  return _internal_state();
}
inline void Snapshot::_internal_set_state(::google::bigtable::admin::v2::Snapshot_State value) {
  
  state_ = value;
}
inline void Snapshot::set_state(::google::bigtable::admin::v2::Snapshot_State value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Snapshot.state)
}

// string description = 7;
inline void Snapshot::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Snapshot::description() const {
  // @@protoc_insertion_point(field_get:google.bigtable.admin.v2.Snapshot.description)
  return _internal_description();
}
inline void Snapshot::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:google.bigtable.admin.v2.Snapshot.description)
}
inline std::string* Snapshot::mutable_description() {
  // @@protoc_insertion_point(field_mutable:google.bigtable.admin.v2.Snapshot.description)
  return _internal_mutable_description();
}
inline const std::string& Snapshot::_internal_description() const {
  return description_.GetNoArena();
}
inline void Snapshot::_internal_set_description(const std::string& value) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Snapshot::set_description(std::string&& value) {
  
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.bigtable.admin.v2.Snapshot.description)
}
inline void Snapshot::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.bigtable.admin.v2.Snapshot.description)
}
inline void Snapshot::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.bigtable.admin.v2.Snapshot.description)
}
inline std::string* Snapshot::_internal_mutable_description() {
  
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Snapshot::release_description() {
  // @@protoc_insertion_point(field_release:google.bigtable.admin.v2.Snapshot.description)
  
  return description_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Snapshot::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:google.bigtable.admin.v2.Snapshot.description)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace admin
}  // namespace bigtable
}  // namespace google

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState>() {
  return ::google::bigtable::admin::v2::Table_ClusterState_ReplicationState_descriptor();
}
template <> struct is_proto_enum< ::google::bigtable::admin::v2::Table_TimestampGranularity> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::bigtable::admin::v2::Table_TimestampGranularity>() {
  return ::google::bigtable::admin::v2::Table_TimestampGranularity_descriptor();
}
template <> struct is_proto_enum< ::google::bigtable::admin::v2::Table_View> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::bigtable::admin::v2::Table_View>() {
  return ::google::bigtable::admin::v2::Table_View_descriptor();
}
template <> struct is_proto_enum< ::google::bigtable::admin::v2::Snapshot_State> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::bigtable::admin::v2::Snapshot_State>() {
  return ::google::bigtable::admin::v2::Snapshot_State_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fbigtable_2fadmin_2fv2_2ftable_2eproto
