// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_initialClient
int C_initialClient(SEXP R_project, SEXP R_creds);
RcppExport SEXP _googleCloudStorage_C_initialClient(SEXP R_projectSEXP, SEXP R_credsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_project(R_projectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_creds(R_credsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_initialClient(R_project, R_creds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_googleCloudStorage_C_initialClient", (DL_FUNC) &_googleCloudStorage_C_initialClient, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_googleCloudStorage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
