# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_set_credential <- function(R_cred) {
    invisible(.Call(`_googleCloudStorage_C_set_credential`, R_cred))
}

C_set_project <- function(R_project_name) {
    invisible(.Call(`_googleCloudStorage_C_set_project`, R_project_name))
}

C_get_bucket_number <- function() {
    .Call(`_googleCloudStorage_C_get_bucket_number`)
}

C_get_bucket_names <- function() {
    .Call(`_googleCloudStorage_C_get_bucket_names`)
}

